// Mock data for NEXT_PUBLIC_USE_MOCK=true (spec M6.1)
import type {
  Place,
  RecommendResult,
  HotelVerifyResult,
  Itinerary,
} from './types'

export const mockPlaces: Place[] = [
  {
    id: 1,
    user_session_id: 'dev',
    name: '永康牛肉麵',
    category: 'food',
    lat: 25.0329,
    lng: 121.5299,
    address: '台北市大安區永康街31號',
    description: '知名老店，半筋半肉麵是招牌',
    source_type: 'reels_url',
    source_url: 'https://www.instagram.com/reel/example',
    hotel_legal_status: null,
    created_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 2,
    user_session_id: 'dev',
    name: '台北君悅酒店',
    category: 'hotel',
    lat: 25.0330,
    lng: 121.5654,
    address: '台北市信義區松壽路2號',
    description: '五星級旅館，信義區',
    source_type: 'reels_url',
    source_url: null,
    hotel_legal_status: 'legal',
    created_at: '2025-01-01T11:00:00Z',
  },
  {
    id: 3,
    user_session_id: 'dev',
    name: '大稻埕碼頭',
    category: 'attraction',
    lat: 25.0566,
    lng: 121.5085,
    address: '台北市大同區環河北路一段',
    description: '夕陽河岸景觀，假日有貨櫃市集',
    source_type: 'image',
    source_url: null,
    hotel_legal_status: null,
    created_at: '2025-01-02T09:00:00Z',
  },
  {
    id: 4,
    user_session_id: 'dev',
    name: '某某日租套房',
    category: 'hotel',
    lat: 25.0470,
    lng: 121.5170,
    address: '台北市萬華區成都路',
    description: '社群推薦的便宜住宿',
    source_type: 'text',
    source_url: null,
    hotel_legal_status: 'illegal',
    created_at: '2025-01-02T18:00:00Z',
  },
]

export const mockRecommendations: RecommendResult[] = [
  {
    attraction: {
      id: 101,
      name: '富錦街咖啡',
      category: 'food',
      lat: 25.0559,
      lng: 121.5541,
      address: '台北市松山區富錦街',
      description: '老宅改建，手沖咖啡',
      tags: ['咖啡', '老宅'],
    },
    reason: '同樣是巷弄內的特色小店',
    score: 0.18,
  },
  {
    attraction: {
      id: 102,
      name: '迪化街老屋茶館',
      category: 'food',
      lat: 25.0570,
      lng: 121.5095,
      address: '台北市大同區迪化街一段',
      description: '日治時期街屋改建，台灣茶與點心',
      tags: ['茶館', '老屋'],
    },
    reason: '延續大稻埕的老屋氛圍',
    score: 0.21,
  },
  {
    attraction: {
      id: 103,
      name: '四四南村',
      category: 'attraction',
      lat: 25.0327,
      lng: 121.5614,
      address: '台北市信義區松勤街50號',
      description: '眷村文創園區，可眺望 101',
      tags: ['文創', '眷村'],
    },
    reason: '信義區一帶適合下午散步的點',
    score: 0.27,
  },
]

export const mockHotelVerify: HotelVerifyResult = {
  status: 'illegal',
  match: null,
  alternatives: [
    { id: 11, name: '台北凱撒大飯店', address: '台北市中正區忠孝西路一段38號' },
    { id: 12, name: '台北六福萬怡酒店', address: '台北市南港區忠孝東路七段359號' },
    { id: 13, name: '台北君品酒店', address: '台北市大同區承德路一段3號' },
  ],
}

export const mockItinerary: Itinerary = {
  id: 1,
  total_duration_hours: 9,
  stops: [
    {
      time: '09:30',
      place_id: 3,
      name: '大稻埕碼頭',
      duration_min: 60,
      transport_to_next: 'MRT 約 15 分鐘',
      note: '早晨河岸散步，避開正午高溫',
      lat: 25.0566,
      lng: 121.5085,
      address: '台北市大同區環河北路一段',
    },
    {
      time: '11:00',
      place_id: 102,
      name: '迪化街老屋茶館',
      duration_min: 75,
      transport_to_next: '步行 8 分鐘',
      note: '搭配台灣茶與午前點心',
      lat: 25.0570,
      lng: 121.5095,
      address: '台北市大同區迪化街一段',
    },
    {
      time: '12:30',
      place_id: 1,
      name: '永康牛肉麵',
      duration_min: 60,
      transport_to_next: 'MRT 約 12 分鐘',
      note: '經典午餐，建議避開 13:00 高峰',
      lat: 25.0329,
      lng: 121.5299,
      address: '台北市大安區永康街31號',
    },
    {
      time: '14:00',
      place_id: 101,
      name: '富錦街咖啡',
      duration_min: 90,
      transport_to_next: '計程車 10 分鐘',
      note: '下午手沖時段',
      lat: 25.0559,
      lng: 121.5541,
      address: '台北市松山區富錦街',
    },
    {
      time: '16:00',
      place_id: 103,
      name: '四四南村',
      duration_min: 90,
      transport_to_next: '步行 5 分鐘',
      note: '眺望 101，黃昏拍照',
      lat: 25.0327,
      lng: 121.5614,
      address: '台北市信義區松勤街50號',
    },
    {
      time: '18:00',
      place_id: 2,
      name: '台北君悅酒店',
      duration_min: 0,
      transport_to_next: '入住',
      note: '今日入住點',
      lat: 25.0330,
      lng: 121.5654,
      address: '台北市信義區松壽路2號',
    },
  ],
}
